//路由的基本信息

export default [
		{	name:"search",
			path:'/search/:keyword?',
			component:()=>import('@/pages/Search'),
			meta:{show:true,isAuth:true}
		},
		{
			path:'/home',
			component:()=>import('@/pages/Home'),
			meta:{show:true,isAuth:true}
		},
        {
			//@/pages/Login
			path:'/login',
			component:()=>import('@/pages/Login'),
			meta:{show:false,isAuth:true}
		},
        {
			//@/pages/Register
			path:'/register',
			component:()=>import('@/pages/Register'),
			meta:{show:false,isAuth:true}
		},
		{
			path:'/detail',
			component:()=>import('@/pages/Detail'),
			meta:{show:false,isAuth:true}
		},
		{
			path:'/addcartsuccess',
			name:'addcartsuccess',
			component:()=>import('@/pages/AddCartSuccess'),
			meta:{show:false,isAuth:true}
		},
		{
			path:'/shopcart',
			component:()=>import('@/pages/ShopCart'),
			meta:{show:false,isAuth:true}
		},
		{
			path:'/trade',
			component:()=>import('@/pages/Trade'),
			meta:{show:false,isAuth:false},
			//路由独享守卫
			beforeEnter: (to, from, next) => {
				//保证去交易页面的必须是从购物车来的
				if(from.path=="/shopcart"){
					next()
				}else{
					//中断当前的导航（理解为重置）
					//如果浏览器的url改变了，url地址重置到form路由对应地址
					next(false)
				}
			}
		},
		{
			path:'/pay',
			component:()=>import('@/pages/Pay'),
			meta:{show:false,isAuth:false},
			beforeEnter: (to, from, next) => {
				if(from.path=="/trade"){
					next()
				}else{
					next(false)
				}
			}
		},
		{
			path:'/paysuccess',
			component:()=>import('@/pages/PaySuccess'),
			meta:{show:false,isAuth:false}
		},
		{
			path:'/center',
			component:()=>import('@/pages/Center'),
			meta:{show:false,isAuth:false},
			//二级路由组件(路径开头不要反斜杠)
			children:[
				{
					path:'myorder',
					component:()=>import('@/pages/Center/MyOrder')
				},
				{
					path:'grouporder',
					component:()=>import('@/pages/Center/GroupOrder')
				},
				//路由重定向
				{
					path:'/center',
					redirect:"/center/myorder"
				}
			]
		},
		//重定向，在项目跑起来的时候，访问/，立马定向到首页
		{
			path:'*',
			redirect:"/home"
		},
	]
